# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno
name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno install

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #   run: deno fmt --check

      - name: Run linter
        run: deno task lint

      # - name: Run tests
      #   run: deno test -A

      - name: Build
        run: deno task build

      - name: Deploy
        env:
          BRANCH_NAME: ${{ vars.BRANCH_NAME }}
          AMPLIFY_APP_ID: ${{ vars.AMPLIFY_APP_ID }}
          WEBHOOK_ID: ${{ vars.WEBHOOK_ID }}
          TOKEN: ${{ vars.TOKEN }}
        run: |
          deno run -A npm:ampx pipeline-deploy --branch $BRANCH_NAME --app-id $AMPLIFY_APP_ID
          curl -X POST -d {} "https://webhooks.amplify.ap-southeast-1.amazonaws.com/prod/webhooks?id=$WEBHOOK_ID&token=$TOKEN&operation=startbuild" -H "Content-Type:application/json"
